### ISSUE TITLE
Link to the blog in Readme.md goes to a 404

### ISSUE THREAD

**Issue by alemangui** [jbum/CDMS#1]
The link in the readme.md is incorrect and links to a 404.

The current link URL is: http://krazydad.com/blog/2015/07/13/cycloid-drawin%E2%80%A6ine-simulation/

I suppose the correct link URL is: http://krazydad.com/blog/2015/07/12/cycloid-drawing-machine-simulation/

Cheers

**Comment by jbum** [comment]
Fixed thanks!

**Comment by jbum** [comment]
Thanks for catching that - fixed.
