### ISSUE TITLE
Snapshot Not working in Chrome (possible webkit issue)

### ISSUE THREAD

**Issue by alisneaky** [jbum/CDMS#3]
Trying to take a snapshot and all I get is a new untitled browser tab with nothing else. no downloads etc. Nothing in clipboard either.

Any help would be appreciated. Ps. amazing piece of code :)

**Comment by jbum** [comment]
Thanks for catching that.  I'm guessing you are using Chrome (or maybe
Safari).  It appears to be broken in those, perhaps due to a recent change.
I just tested snapshots in Firefox and that worked....  Glad you're liking
it!

Jim

**Comment by alisneaky** [comment]
You are correct in your assumption of Chrome :) thanks for the quick reply! will try FF.

**Comment by jbum** [comment]
Thanks for catching that.  I'm guessing you are using Chrome.  Snapshots appear to be broken in Chrome, perhaps due to a recent change.  I just tested snapshots in Firefox and Safari and both worked., so there's your work-around.  I'll see if I can figure out what's going on with chrome...

Glad you're liking it!

**Comment by skyline2016** [comment]
I tried chrome, edge, safari, none of them the snapshot function is working anymore. Will this code still maintain? This is a great piece of work.

**Comment by jbum** [comment]
I think I know what the problem is. Had a similar issue on my interactive puzzle site, which I had to patch a few months ago. I’ll repair it when I get a moment.

**Comment by jbum** [comment]
Patched on live site and here.  Works in Chrome now, but you may need to do a hard reload so it pulls the latest version of processing.js.    Note: Processing.js is no longer supported, so I should probably port the whole thing to p5.js, but in the meantime, I patched the save() function.
